#!/bin/sh

# simple wrapper for lxc-start

NAME="$1"
test -n "$NAME" || { echo "Usage: $0 <name>"; exit 1; }

d="/var/lib/lxc/$NAME"
c="$d/config"
test -f "$c" || { echo "ERROR: $c does not exist."; exit 1; }

echo "Try to start $NAME..."
lxc-start -n "$NAME" -c "$d/console.log" -o "$d/lxc.log" -d

echo "Try to setup route..."
d0=`dirname $0`
$d0/lxc-ifup "$NAME"

echo "Done."

## EOF ##
