#!/bin/sh

Die() { echo "lxc-ifup: ${iface}: Error: $*"; exit 1; }

if test $# = 2; then
	iface="$1"
	ipaddr="$2"
elif test $# = 1; then
	topdir="/var/lib/lxc/$1"
	debnet="$topdir/rootfs/etc/network/interfaces"
	config="$topdir/config"
	test -f "$config" || Die "$config does not exist."

	 iface="$(grep ^lxc.network.veth.pair $config | sed -e 's,.*= *,,')"
	ipaddr="$(grep ^lxc.network.ipv4      $config | sed -e 's,.*= *,,')"
	test -z "$ipaddr" && ipaddr="$(grep -w address $debnet | sed -e 's,.*[^0-9.],,')"
	test -z "$ipaddr" && Die "cannot detect container IP."
	#echo "DEBUG: iface=$iface, ipaddr=$ipaddr"; exit
else
	echo "Usage: $0 vethXXX <container-ipaddr>"
	echo "Usage: $0 <container-name>"
	exit 1
fi

test -n "$iface" || Die "missing interface name.";

for a in $ipaddr; do
	me="$(ip route get "$a"      | grep -- ' src '      | head -1 | sed -e 's,.* src ,,' -e 's, .*,,')"
	test -n "$me" || Die "cannot detect IP for using as router."

	dv="$(ip route get "$a"      | grep -- ' dev '      | head -1 | sed -e 's,.* dev ,,' -e 's, .*,,')"
	test -n "$dv" || Die "cannot detect base interface."

	mm="$(ip addr list dev "$dv" | grep -- " inet $me/" | head -1 | sed -e 's,.*/,,' -e 's, .*,,')"
	test -n "$mm" || Die "cannot detect netmask."

	if arping -I "$dv" -qc3 "$ipaddr"; then
		a="$(ip neighbor show to "$ipaddr" dev "$dv")"
		Die "$ipaddr seems already available on $dv as $a."
	fi

	sysctl "net.ipv4.conf.$iface.proxy_arp=1" > /dev/null

	ip link set "$iface" up
	ip addr add "$me/$mm" dev "$iface"

	# Remove route automatically added by previous command..
	ip route list proto kernel scope link dev "$iface" \
	| while read dest unused; do
		ip route delete "$dest" dev "$iface"
	done

	ip route add "$a/32" dev "$iface" src "$me"

	logger -s "lxc-ifup: $iface: ip=$a, me=$me/$mm, basedev=$dv."
done

## EOF ##
